name: harhar
version: 2023.10.20
description: |
  Parser and analyzer for https://w3c.github.io/web-performance/specs/HAR/Overview.html files

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.4.2
