name: harhar
version: 2023.11.28
description: Parser and analyzer for https://w3c.github.io/web-performance/specs/HAR/Overview.html files

environment:
  sdk: ^3.1.0

dev_dependencies:
  embed: ^1.2.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  test: ^1.24.9

dependencies:
  args: ^2.4.2
  dart_console: ^1.2.0
  duration: ^3.0.13
  embed_annotation: ^1.2.0
  json_annotation: ^4.8.1
